import './index.html';
import './style.scss';
import $ from "jquery";
// window.jQuery = $;
// require("@fancyapps/fancybox");
// import './js/slider.js';
// import './js/mask-number.js';
// import './js/map.js';
import './img/map.svg';
import './js/tabs.js';
import './js/burger-menu.js';
import './js/border-animatiom.js';